import type { MapRegion, WeatherSnapshot } from "../types";

export const MAP_REGIONS: readonly MapRegion[] = [
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    center: { lat: 38.7223, lng: -9.1393 },
    markers: [
      {
        id: "lisbon-dest",
        type: "destination",
        label: "Lisbon",
        subtitle: "Coastal capital",
        lat: 38.7223,
        lng: -9.1393,
        href: "/destinations/lisbon",
      },
      {
        id: "lisbon-cafe-1",
        type: "cafe",
        label: "Chiado espresso bar",
        subtitle: "Specialty café",
        lat: 38.7105,
        lng: -9.1425,
      },
      {
        id: "lisbon-attr-1",
        type: "attraction",
        label: "Alfama miradouro",
        subtitle: "Viewpoint",
        lat: 38.7125,
        lng: -9.1305,
      },
      {
        id: "lisbon-guide-1",
        type: "guide",
        label: "Lisbon coastal cafés",
        subtitle: "Guide",
        lat: 38.717,
        lng: -9.15,
        href: "/guides",
      },
    ],
    nearbyCafes: ["Terrace espresso near Chiado", "LX Factory work café"],
    nearbyAttractions: ["Alfama", "Belém", "Time Out Market"],
    nearbyGuides: ["Lisbon coastal cafés", "Solo week in Lisbon"],
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    center: { lat: 48.2082, lng: 16.3738 },
    markers: [
      {
        id: "vienna-dest",
        type: "destination",
        label: "Vienna",
        subtitle: "Coffeehouse capital",
        lat: 48.2082,
        lng: 16.3738,
        href: "/destinations/vienna",
      },
      {
        id: "vienna-cafe",
        type: "cafe",
        label: "Café Central",
        subtitle: "Historic café",
        lat: 48.2103,
        lng: 16.365,
        href: "/cafes/cafe-central-vienna",
      },
      {
        id: "vienna-attr",
        type: "attraction",
        label: "Ringstrasse",
        subtitle: "Scenic walk",
        lat: 48.203,
        lng: 16.368,
      },
    ],
    nearbyCafes: ["Café Central", "Neighborhood specialty bar"],
    nearbyAttractions: ["Museum Quarter", "Schönbrunn"],
    nearbyGuides: ["Vienna coffeehouse weekend"],
  },
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    center: { lat: 35.0116, lng: 135.7681 },
    markers: [
      {
        id: "kyoto-dest",
        type: "destination",
        label: "Kyoto",
        subtitle: "Temples & quiet cafés",
        lat: 35.0116,
        lng: 135.7681,
        href: "/destinations/kyoto",
      },
      {
        id: "kyoto-cafe",
        type: "cafe",
        label: "Blue Bottle Kyoto",
        subtitle: "Specialty",
        lat: 35.004,
        lng: 135.768,
        href: "/cafes/blue-bottle-kyoto",
      },
      {
        id: "kyoto-attr",
        type: "attraction",
        label: "Arashiyama",
        subtitle: "Bamboo grove",
        lat: 35.0094,
        lng: 135.667,
      },
    ],
    nearbyCafes: ["Blue Bottle Kyoto", "Temple-side pour-over"],
    nearbyAttractions: ["Fushimi Inari", "Philosopher’s Path"],
    nearbyGuides: ["Kyoto quiet cafés"],
  },
  {
    id: "addis",
    name: "Addis Ababa",
    country: "Ethiopia",
    center: { lat: 9.032, lng: 38.7469 },
    markers: [
      {
        id: "addis-dest",
        type: "destination",
        label: "Addis Ababa",
        subtitle: "Coffee origins",
        lat: 9.032,
        lng: 38.7469,
        href: "/destinations/addis-ababa",
      },
      {
        id: "addis-cafe",
        type: "cafe",
        label: "Tomoca Coffee",
        subtitle: "Historic café",
        lat: 9.022,
        lng: 38.752,
        href: "/cafes/tomoca-coffee-addis",
      },
    ],
    nearbyCafes: ["Tomoca Coffee", "Ceremony host"],
    nearbyAttractions: ["National Museum", "Merkato"],
    nearbyGuides: ["Addis Ababa coffee origins"],
  },
];

export function getWeatherForCity(city: string): WeatherSnapshot {
  const presets: Record<string, WeatherSnapshot> = {
    Lisbon: {
      city: "Lisbon",
      country: "Portugal",
      currentC: 22,
      condition: "Partly cloudy",
      humidity: 58,
      windKph: 14,
      bestSeason: "March–June & September–October",
      forecast: [
        { label: "Today", highC: 23, lowC: 16, condition: "Partly cloudy", icon: "partly" },
        { label: "Tue", highC: 24, lowC: 17, condition: "Sunny", icon: "sun" },
        { label: "Wed", highC: 21, lowC: 15, condition: "Light rain", icon: "rain" },
        { label: "Thu", highC: 22, lowC: 15, condition: "Cloudy", icon: "cloud" },
        { label: "Fri", highC: 23, lowC: 16, condition: "Sunny", icon: "sun" },
      ],
    },
    Vienna: {
      city: "Vienna",
      country: "Austria",
      currentC: 18,
      condition: "Clear",
      humidity: 52,
      windKph: 11,
      bestSeason: "April–June & September",
      forecast: [
        { label: "Today", highC: 19, lowC: 10, condition: "Clear", icon: "sun" },
        { label: "Tue", highC: 20, lowC: 11, condition: "Partly cloudy", icon: "partly" },
        { label: "Wed", highC: 17, lowC: 9, condition: "Cloudy", icon: "cloud" },
        { label: "Thu", highC: 16, lowC: 8, condition: "Light rain", icon: "rain" },
        { label: "Fri", highC: 18, lowC: 9, condition: "Sunny", icon: "sun" },
      ],
    },
    Kyoto: {
      city: "Kyoto",
      country: "Japan",
      currentC: 26,
      condition: "Humid",
      humidity: 72,
      windKph: 9,
      bestSeason: "March–May & October–November",
      forecast: [
        { label: "Today", highC: 27, lowC: 20, condition: "Humid", icon: "cloud" },
        { label: "Tue", highC: 28, lowC: 21, condition: "Partly cloudy", icon: "partly" },
        { label: "Wed", highC: 29, lowC: 22, condition: "Sunny", icon: "sun" },
        { label: "Thu", highC: 26, lowC: 20, condition: "Showers", icon: "rain" },
        { label: "Fri", highC: 27, lowC: 20, condition: "Partly cloudy", icon: "partly" },
      ],
    },
  };

  return (
    presets[city] ?? {
      city,
      country: "Worldwide",
      currentC: 21,
      condition: "Mild",
      humidity: 55,
      windKph: 12,
      bestSeason: "Shoulder seasons for comfortable walking and café hopping",
      forecast: [
        { label: "Today", highC: 22, lowC: 14, condition: "Mild", icon: "partly" },
        { label: "Tue", highC: 23, lowC: 15, condition: "Sunny", icon: "sun" },
        { label: "Wed", highC: 21, lowC: 14, condition: "Cloudy", icon: "cloud" },
        { label: "Thu", highC: 20, lowC: 13, condition: "Light rain", icon: "rain" },
        { label: "Fri", highC: 22, lowC: 14, condition: "Sunny", icon: "sun" },
      ],
    }
  );
}
